### ISSUE TITLE
Feature & Design thread

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-mixer#4]
In the mixer app, I image each radio channel being the sources, `inputs` in place of vinyl player, cdj, tape, radio, mp3 player - any source generating input sounds.

Those inputs would be plugged in the `mixer`, which lies in their middle and controls the sound processing after it is generated by them.

Then as output, we're going for the browsers', sound cards.

On this png you can see, 2*3 frequencies equilizers (high, mid, low), 2 volume faders, 1 crossfader.
Some of those features cannot be technically achieved yet (equilizers).

![interface png](https://cloud.githubusercontent.com/assets/1502484/25693058/3f368260-30a7-11e7-8435-7653fbd509ce.png)
_interface test ([source svg](https://drive.google.com/drive/u/0/folders/0B1EFH8Llhq5yMXFMMzRJeGZRTU0), editied with inkspace - linux)_

Feature ideas:
- a way to select which radio channel is assigned to which deck
- a way to change the fader's curve (here it's linear, could have a faster cut shaped)
- possibility to add more decks (3rd, 4th...)  (play beats + accapela + textures! ! ! ! !)
- reset buttons, to center the faders and knobs to their default position (touch friendly) 
- an interface that works well from mobile to tv
- a way to control mix.r4.com from two different devices (playing on a tv, controlled by phone)
- skins!!!! (for the players and the mixer)
- join a mix, a url to share to join and listen to a mix from anywhere

**Comment by hellerve** [comment]
Just want to give my two cents here. I would be happy to help with the implementation of the equalizers and faders. I think a lot of the implementation can be pulled from [a project that I worked on a while ago](https://github.com/VetoProjects/supersaw).

Just a quick question: why do you say it's not achievable technically?

**Comment by hugurp** [comment]
Cool!

Do you think it is possible to equalize/apply effects to the sound output of a Youtube/iframe?

That would be amazing!

**Comment by hellerve** [comment]
We can't just wrap the iframe, no. We would have to access the contents within the iframe, which might be a bit fiddly. Apparently there are [frameworks](https://plyr.io/#youtube) that make it easier, but it would require a rewrite of the iframe, and I'm not sure we want that. It _would_ , however also give us the opportunity to style the video player, which might be interesting.
